name: compliments_app
description: compliments app


publish_to: 'none'

version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.1.0
  colours: ^0.0.2
  path_provider: ^2.0.15
  share_plus: ^7.0.0
  screenshot: ^2.1.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  go_router: ^14.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/compliments.json

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


